import './globals.css';
import { Inter } from 'next/font/google';
import Header from './components/header/header';
const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Next Blog Basic',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={`${inter.className}`}>
        <Header />
        <main className=''>{children}</main>
      </body>
    </html>
  );
}
